# Generated by Django 5.2.1 on 2025-05-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="addressline2",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
