# Generated by Django 5.2.1 on 2025-06-14 01:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_housing_alter_bookmark_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoommateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("looking_for_roommate", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True)),
                (
                    "age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("n/a", "Prefer not to say"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("pets_ok", models.BooleanField(db_index=True, default=False)),
                ("smoker_ok", models.BooleanField(db_index=True, default=False)),
                (
                    "cleanliness",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                (
                    "noise_tolerance",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                (
                    "sleep_schedule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Early Bird", "Early Bird"),
                            ("Night Owl", "Night Owl"),
                            ("Flexible", "Flexible"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
    ]
