# Generated by Django 5.2.1 on 2025-07-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_userverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="housing",
            name="commute",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="housing",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="housing",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
