# Generated by Django 5.2.1 on 2025-07-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_housing_commute_housing_description_housing_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="background_image",
            field=models.FileField(
                blank=True, null=True, upload_to="campus_backgrounds/"
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="campus",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="campus_logos/"),
        ),
        migrations.AddField(
            model_name="campus",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
