# Generated by Django 5.2.1 on 2025-07-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_campus_background_image_campus_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="housing",
            name="thumbnail",
            field=models.FileField(
                blank=True, null=True, upload_to="housing_thumbnails/"
            ),
        ),
    ]
