# Generated by Django 5.2.1 on 2025-07-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_housing_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housing",
            name="thumbnail",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
