# Generated by Django 5.2.1 on 2025-07-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_housing_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="housing",
            name="lowest_rent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
