# Generated by Django 5.2.1 on 2025-07-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_housing_lowest_rent"),
    ]

    operations = [
        migrations.AddField(
            model_name="housing",
            name="image_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
