# Generated by Django 5.2.1 on 2025-07-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_housing_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="housing",
            name="bathrooms",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="housing",
            name="bedrooms",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="housing",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
