US_STATE_CHOICES = [
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
]

APARTMENT_TAG_CHOICES = [
    ("close_to_campus", "Close to Campus"),
    ("responsive_maintenance", "Responsive Maintenance"),
    ("affordable", "Affordable"),
    ("thin_walls", "Thin Walls"),
    ("party_atmosphere", "Party Atmosphere"),
    ("secure_building", "Secure Building"),
    ("noisy_neighbors", "Noisy Neighbors"),
    ("all_inclusive_utilities", "All-Inclusive Utilities"),
    ("helpful_office_staff", "Helpful Office Staff"),
    ("modern_appliances", "Modern Appliances"),
    ("walkable_area", "Walkable Area"),
    ("unresponsive_management", "Unresponsive Management"),
    ("quiet_and_chill", "Quiet & Chill"),
    ("free_parking", "Free Parking"),
    ("frequent_pest_issues", "Frequent Pest Issues"),
]
